cache: bundler
language: ruby
rvm:
  - 2.4
  - 2.5
  - ruby-head
script: bundle exec rspec
sudo: false

bundler_args: --without development

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true
  include:
    - rvm: 2.6
      before_script:
        - bundle exec danger
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - rvm: jruby-9.2.8.0
      jdk: openjdk8
